#!/usr/bin/env php
<?php

/**
 * Class spartan
 *
 * @package ${NAMESPACE}
 * @author  Mohammed Ashour <ashoms0a@gmail.com>
 * @link    http://www.coderavine.com/
 */

require __DIR__ . '/vendor/autoload.php';

use Sparta\Console\Commands\MakeValidatorCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new MakeValidatorCommand());
$application->run();
